"""One or two plain-English sentences per company, for the hover card on the game screen.

Written for someone new to the stock market: what the company does, using products they
might recognize. Plain data like universes.py, so it works offline. The text describes the
company today, which may not match a stretch of history years ago.
"""

DESCRIPTIONS: dict[str, str] = {
    "AAPL": "Makes the iPhone, Mac computers, iPad and Apple Watch, and sells services like the App Store and Apple Music.",
    "ABNB": "Runs a website and app where people rent out their homes or rooms to travelers.",
    "ADBE": "Makes software for creative work, like Photoshop, and the PDF tools many offices use.",
    "ADI": "Makes chips that turn real-world signals like sound, heat and motion into data for cars, factories and phones.",
    "ADP": "Runs payroll for other businesses, making sure workers get paid and taxes are filed.",
    "ADSK": "Makes design software, like AutoCAD, that architects and engineers use to plan buildings and products.",
    "AEP": "An electric company that delivers power to millions of homes and businesses in 11 U.S. states.",
    "AMAT": "Builds the huge machines that factories use to make computer chips.",
    "AMD": "Designs computer chips, both processors and graphics chips, for PCs, game consoles and data centers.",
    "AMGN": "A biotech company that makes medicines for illnesses like cancer, bone loss and heart disease.",
    "AMZN": "The giant online store. It also runs Amazon Web Services, which rents computing power to other companies.",
    "APP": "Makes software that helps app and game makers advertise and earn money from their apps.",
    "ARM": "Designs the chip blueprints used in almost every smartphone. Other companies pay to use its designs.",
    "ASML": "A Dutch company that builds the most advanced machines used to make computer chips.",
    "AVGO": "Makes chips for networking, wireless and data centers, and also sells business software.",
    "AXON": "Makes Tasers, police body cameras and the software police use to store evidence.",
    "BIIB": "A biotech company that makes medicines for brain and nerve diseases like multiple sclerosis and Alzheimer's.",
    "BKNG": "Runs travel websites like Booking.com, Priceline and Kayak for booking hotels, flights and rental cars.",
    "BKR": "Provides equipment and services that help oil and gas companies drill and move energy.",
    "CCEP": "Bottles and sells Coca-Cola drinks across Europe, Australia and parts of Asia.",
    "CDNS": "Makes the software engineers use to design computer chips.",
    "CDW": "Sells computers, software and tech support to businesses, schools and governments.",
    "CEG": "The biggest producer of nuclear power in the U.S., selling electricity to homes and businesses.",
    "CHTR": "Provides internet, cable TV and phone service under the Spectrum brand.",
    "CMCSA": "Provides Xfinity internet and cable, and owns NBC, Universal movie studios and Universal theme parks.",
    "COIN": "Runs a popular app for buying, selling and storing cryptocurrencies like Bitcoin.",
    "COST": "Runs Costco warehouse stores, where members pay a yearly fee to buy groceries and goods in bulk at low prices.",
    "CPRT": "Runs online auctions that sell used and wrecked cars, often for insurance companies.",
    "CRM": "Salesforce makes cloud software that helps companies keep track of their customers and sales.",
    "CRWD": "Makes cybersecurity software that protects company computers from hackers.",
    "CSCO": "Makes the networking equipment, like routers and switches, that connects computers to each other and the internet.",
    "CSGP": "Runs real estate websites and data services, including Apartments.com and Homes.com.",
    "CSX": "A railroad company that moves goods by train across the eastern United States.",
    "CTAS": "Rents and cleans work uniforms, and supplies businesses with floor mats, first-aid kits and safety gear.",
    "CTSH": "Helps big companies with tech projects, like building software and running their computer systems.",
    "DASH": "Runs the DoorDash app, which delivers food and other goods from local restaurants and stores.",
    "DDOG": "Makes software that watches companies' apps and servers and warns them when something breaks.",
    "DXCM": "Makes small wearable sensors that let people with diabetes check their blood sugar all day.",
    "EA": "A video game company that makes games like EA Sports FC, Madden NFL and The Sims.",
    "EXC": "An energy company that delivers electricity and gas to millions of customers in several U.S. cities.",
    "FANG": "An oil and gas company that drills for oil in West Texas.",
    "FAST": "Sells nuts, bolts, tools and safety supplies to factories and construction companies.",
    "FTNT": "Makes firewalls and security software that protect company networks from cyberattacks.",
    "GEHC": "Makes medical equipment like MRI, CT and ultrasound machines used in hospitals.",
    "GFS": "Manufactures computer chips for other companies that design them.",
    "GILD": "A drug company known for medicines that treat HIV, hepatitis and some cancers.",
    "GOOG": "Alphabet owns Google Search, YouTube, Android and Google Cloud, and makes most of its money from ads. These Class C shares don't come with voting rights.",
    "GOOGL": "Alphabet owns Google Search, YouTube, Android and Google Cloud, and makes most of its money from ads. These Class A shares let owners vote on company decisions.",
    "HON": "A large manufacturer that makes airplane parts, building controls, safety equipment and factory tools.",
    "IBM": "A long-running tech company that sells business software, cloud services and consulting, plus large mainframe computers.",
    "IDXX": "Makes tests and lab equipment that veterinarians use to check the health of pets and farm animals.",
    "INSM": "A biotech company that develops medicines for rare lung diseases.",
    "INTC": "Designs and makes computer processors, the \"brains\" inside many PCs and servers.",
    "INTU": "Makes money software like TurboTax, QuickBooks and Credit Karma.",
    "ISRG": "Makes the da Vinci robot that helps surgeons operate through small cuts.",
    "KDP": "Sells drinks like Dr Pepper, Snapple and Canada Dry, and makes Keurig coffee machines and pods.",
    "KHC": "Makes packaged foods like Heinz ketchup, Kraft Mac & Cheese and Oscar Mayer.",
    "KLAC": "Makes machines that inspect computer chips for tiny defects while they are being made.",
    "LIN": "Supplies gases like oxygen, nitrogen and hydrogen to hospitals, factories and labs.",
    "LRCX": "Builds machines that chip factories use to etch and layer materials onto silicon wafers.",
    "MAR": "Runs and franchises hotels around the world, including Marriott, Sheraton and Ritz-Carlton.",
    "MCHP": "Makes small chips that control everyday things like appliances, cars and factory equipment.",
    "MDLZ": "Makes snacks like Oreo cookies, Cadbury chocolate and Ritz crackers.",
    "MELI": "Runs the biggest online store and digital payment app in Latin America.",
    "META": "Owns Facebook, Instagram and WhatsApp. It makes most of its money from ads and also builds VR headsets.",
    "MNST": "Makes Monster energy drinks and other energy drink brands.",
    "MRVL": "Designs chips that move and store data in data centers, networks and cars.",
    "MSFT": "Makes Windows, Office and the Xbox, and runs Azure, a big cloud computing business.",
    "MSTR": "A software company that has also bought a huge amount of Bitcoin, so its stock often moves with Bitcoin's price.",
    "MU": "Makes memory and storage chips used in computers, phones and data centers.",
    "NFLX": "Runs the Netflix streaming service, where members pay monthly to watch shows and movies.",
    "NOW": "Makes cloud software that helps companies run their IT help desks and office workflows.",
    "NVDA": "Designs graphics chips (GPUs) for gaming and the powerful chips used to train AI.",
    "NXPI": "A Dutch chipmaker whose chips are used in cars, tap-to-pay cards and smart devices.",
    "ODFL": "A trucking company that delivers shipments too small to fill a whole truck.",
    "ON": "Makes power and sensor chips, many of them for electric cars and factories.",
    "ORCL": "Makes database software that businesses use to store their data, and sells cloud computing services.",
    "ORLY": "Runs O'Reilly Auto Parts stores that sell car parts to mechanics and do-it-yourselfers.",
    "PANW": "Makes cybersecurity products that protect company networks and cloud systems from hackers.",
    "PAYX": "Handles payroll, HR and benefits for small and medium-sized businesses.",
    "PCAR": "Builds big trucks under the Kenworth, Peterbilt and DAF brands.",
    "PDD": "Runs the shopping apps Temu and Pinduoduo, known for very low prices.",
    "PEP": "Makes Pepsi and Gatorade, plus snacks and foods like Lay's, Doritos and Quaker oats.",
    "PLTR": "Makes data analysis software used by governments, militaries and large companies.",
    "PYPL": "Runs PayPal and Venmo, apps for sending money and paying online.",
    "QCOM": "Designs chips and wireless technology used in most smartphones.",
    "REGN": "A biotech company that makes medicines for eye diseases, allergies, asthma and cancer.",
    "ROP": "Owns a group of software businesses that each serve a specific industry, like health care or government.",
    "ROST": "Runs Ross Dress for Less stores that sell clothing and home goods at discount prices.",
    "SBUX": "Runs Starbucks coffee shops around the world.",
    "SHOP": "Makes software that lets businesses build and run their own online stores.",
    "SMCI": "Builds computer servers, including powerful machines used for AI.",
    "SNOW": "Makes cloud software that lets companies store and analyze huge amounts of data.",
    "SNPS": "Makes software that engineers use to design and test computer chips.",
    "STX": "Makes hard drives that store huge amounts of data, mostly for data centers.",
    "TEAM": "Makes teamwork software like Jira and Confluence that helps teams plan and track projects.",
    "TMUS": "A wireless company that provides cell phone and home internet service.",
    "TSLA": "Makes electric cars like the Model 3 and Model Y, plus home batteries and solar panels.",
    "TTD": "Runs a platform that helps advertisers buy online ads across websites, apps and streaming TV.",
    "TTWO": "A video game company that makes Grand Theft Auto, NBA 2K and Red Dead Redemption.",
    "TXN": "Makes basic chips used in almost every electronic device, from cars to calculators.",
    "UBER": "Runs the Uber app for ride-hailing and Uber Eats food delivery.",
    "VRSK": "Collects and studies data that insurance companies use to set prices and judge risk.",
    "VRTX": "A biotech company best known for medicines that treat cystic fibrosis.",
    "WBD": "Owns Warner Bros. movie studios, HBO and CNN.",
    "WDAY": "Makes cloud software that companies use to manage their employees, payroll and finances.",
    "XEL": "An electric and gas company serving customers in eight U.S. states, with a lot of wind power.",
    "ZS": "Makes cloud security software that protects workers' internet connections from threats.",
}


def describe(ticker: str, company_name: str | None = None, sector: str | None = None) -> str:
    text = DESCRIPTIONS.get((ticker or "").upper())
    if text:
        return text
    name = company_name or ticker
    return f"{name} is a company in the {sector.lower()} industry." if sector else f"{name} is a publicly traded company."
